on:
  push:
    branches:
      - main

name: Deploy to the Production Environment on main Branch

jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer

    - name: Use Production env
      run: cp env.production .env

    - name: Install vendors
      run: |
        composer install --no-dev --optimize-autoloader
        rm -rf node_modules package-lock.json
        npm install
        npm run build
        npm ci --no-optional
        php artisan route:clear
        php artisan view:clear

    - name: Check disk space on server
      run: |
        ftp -inv 162.240.172.35 <<EOF
        user test@attendance.blvs.uk Ovindu@12
        quote STAT
        bye
        EOF

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 162.240.172.35
        username: test@attendance.blvs.uk
        password: Ovindu@12
        timeout_minutes: 5
        max_attempts: 5
